
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE:-ecommerce}
      # You should definitely change the password in production
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-root}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MARIADB_USER: ${MYSQL_USER:-root}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
