api_platform:
  title: E-Commerce API
  version: 1.0.0
  description: "API for E-Commerce platform"
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header